version: '3.8'

services:
  # Seu container Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8000:80" # Acessar no navegador via porta 8000
    volumes:
      - ./:/var/www/html # Sincroniza seus arquivos com o container
    depends_on:
      - db
    networks:
      - laravel-network

  # Seu container de Banco de Dados
  db:
    image: mariadb:10.6
    container_name: mariadb_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network

# Configurações de Rede e Volumes
networks:
  laravel-network:
    driver: bridge

volumes:
  dbdata: